version: '3.3'

services:
  node:
    image: senseinode/polkadot:with-snap-latest
    container_name: polka-node
    restart: unless-stopped
    ports:
      - 9933:9933
      - 30333:30333
    volumes:
      - data:/data
      - backup:/root/.local/share/polkadot
    environment:
      - SNAP_MODE=true
      - CHAIN=polkadot

volumes:
  data:
  backup:
