version: '3.3'

services:
  node:
    image: senseinode/polkadot:latest # You can use your own build
    restart: unless-stopped
    env_file: .env
    ports:
      - 9933:9933
      - 30333:30333
    volumes:
      - data:/data
      - backup:/root/.local/share/polkadot

volumes:
  data:
  backup: